# Pytorch practice Nil

#tout commenca avec les tensurs

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([4,8])
vector

tensor([4, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor ([[1,2,0],[3,1,5],[3,1,8]])
matrix

tensor([[1, 2, 0],
        [3, 1, 5],
        [3, 1, 8]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([3, 3])

In [11]:
Tensor = torch.tensor([[[1, 2, 0,4],
                       [3, 1, 5, 4],
                       [3, 1, 8, 4]]])

In [12]:
Tensor.ndim

3

In [13]:
Tensor.shape

torch.Size([1, 3, 4])

In [14]:
ranndom_tensor = torch.rand(size = (3,4))
ranndom_tensor,ranndom_tensor.dtype

(tensor([[0.8585, 0.6736, 0.0093, 0.8149],
         [0.7392, 0.8490, 0.7164, 0.6999],
         [0.4516, 0.1487, 0.4243, 0.7015]]),
 torch.float32)

In [15]:
zeros = torch.zeros(size = (3,3))
zeros ,zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [16]:
ones= torch.ones(size = (4,4))
ones,ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [17]:
arrange = torch.arange (0, 10 , 2)
arrange,arrange.ndim

(tensor([0, 2, 4, 6, 8]), 1)

In [18]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten_deprecated, zero_to_ten_deprecated.dtype

<ipython-input-18-e05bf9d1a5ba>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.float32)

In [19]:
start=0
end= 10
step= 1
zero_to_ten = torch.arange(start , end , step)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
float_32_tensor = torch.tensor([[3.0 , 2.0],[3.0 , 2.0],[3.0 , 2.0]],
                               dtype= None,
                               device= None,
                               requires_grad=False)

float_32_tensor, float_32_tensor.shape ,float_32_tensor.ndim, float_32_tensor.device

(tensor([[3., 2.],
         [3., 2.],
         [3., 2.]]),
 torch.Size([3, 2]),
 2,
 device(type='cpu'))

#Operation sur les tenseur

##Addition

In [21]:
tensor_add = torch.rand (4,4)
tensor_add + 10

tensor([[10.2020, 10.2709, 10.0783, 10.8567],
        [10.6591, 10.0290, 10.4231, 10.7525],
        [10.0760, 10.9587, 10.2219, 10.5053],
        [10.9962, 10.8168, 10.6779, 10.9770]])

In [22]:
tensor_add =tensor_add +10
tensor_add

tensor([[10.2020, 10.2709, 10.0783, 10.8567],
        [10.6591, 10.0290, 10.4231, 10.7525],
        [10.0760, 10.9587, 10.2219, 10.5053],
        [10.9962, 10.8168, 10.6779, 10.9770]])

In [23]:
tensor_add -10

tensor([[0.2020, 0.2709, 0.0783, 0.8567],
        [0.6591, 0.0290, 0.4231, 0.7525],
        [0.0760, 0.9587, 0.2219, 0.5053],
        [0.9962, 0.8168, 0.6779, 0.9770]])

In [24]:
tensor_add * 10

tensor([[102.0198, 102.7090, 100.7828, 108.5668],
        [106.5911, 100.2903, 104.2311, 107.5249],
        [100.7603, 109.5867, 102.2192, 105.0528],
        [109.9624, 108.1678, 106.7790, 109.7700]])

In [25]:
tor= torch.add(tensor_add,(-10))
tor

tensor([[0.2020, 0.2709, 0.0783, 0.8567],
        [0.6591, 0.0290, 0.4231, 0.7525],
        [0.0760, 0.9587, 0.2219, 0.5053],
        [0.9962, 0.8168, 0.6779, 0.9770]])

In [26]:
tor @ tor

tensor([[1.0788, 0.8373, 0.7285, 1.2534],
        [0.9341, 1.1996, 0.6679, 1.5355],
        [1.1675, 0.6739, 0.8034, 1.3923],
        [1.7644, 1.7415, 1.2363, 2.7651]])

In [27]:
tor @ tor

tensor([[1.0788, 0.8373, 0.7285, 1.2534],
        [0.9341, 1.1996, 0.6679, 1.5355],
        [1.1675, 0.6739, 0.8034, 1.3923],
        [1.7644, 1.7415, 1.2363, 2.7651]])

#Matrix multiplication

##c'est tout ce dont on a besoin

In [28]:
Matrice1 = torch.rand(3,2)

In [29]:
Matrice1

tensor([[0.1968, 0.6194],
        [0.9009, 0.5626],
        [0.0149, 0.0359]])

In [30]:
Matrice2 = torch.rand(2,3)
Matrice2

tensor([[0.3810, 0.4095, 0.8172],
        [0.0203, 0.5850, 0.9734]])

In [31]:
Matrice1 @ Matrice2

tensor([[0.0876, 0.4430, 0.7637],
        [0.3547, 0.6981, 1.2839],
        [0.0064, 0.0271, 0.0471]])

In [32]:
torch.matmul(Matrice1,Matrice2)

tensor([[0.0876, 0.4430, 0.7637],
        [0.3547, 0.6981, 1.2839],
        [0.0064, 0.0271, 0.0471]])

In [33]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(Matrice1)):
  value += Matrice1[i] * Matrice1[i]
value


CPU times: user 1.26 ms, sys: 0 ns, total: 1.26 ms
Wall time: 2.99 ms


tensor([0.8506, 0.7014])

In [34]:
%%time

torch.matmul(Matrice1,Matrice2)

CPU times: user 61 µs, sys: 12 µs, total: 73 µs
Wall time: 77 µs


tensor([[0.0876, 0.4430, 0.7637],
        [0.3547, 0.6981, 1.2839],
        [0.0064, 0.0271, 0.0471]])

In [35]:
tensor_A = torch.tensor ( [[1,2],[3,4],[5,6]],dtype=torch.float32)
tensor_B = torch.tensor ( [[7,8],[9,10],[11,12]],dtype=torch.float32)
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [36]:
print (tensor_A)
print (tensor_B)
print (tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [37]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [38]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [39]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3, out_features = 6)
x= tensor_A
output = linear(x.T)
x,x.shape,output,output.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 torch.Size([3, 2]),
 tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
         [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
        grad_fn=<AddmmBackward0>),
 torch.Size([2, 6]))

#Finding min, max,mean,sum etc...

In [40]:


# Check for GPU
import torch
torch.cuda.is_available()



True

In [41]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [42]:
torch.cuda.device_count()

1

#Resolution des exercices perso

In [43]:
import torch
tenseur_random = torch.rand (7,7)
tenseur_random

tensor([[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
        [0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811]])

In [44]:
second_tenseur= torch.rand(1,7)
second_tenseur

tensor([[0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155]])

In [45]:
produit = tenseur_random @ second_tenseur.T
produit

tensor([[1.3417],
        [1.9172],
        [2.0426],
        [0.6368],
        [1.8116],
        [1.1753],
        [2.1538]])

In [46]:
torch.manual_seed(0)

In [47]:
tenseur_random_2 = torch.rand (7,7)
tenseur_random_2

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [48]:
second_tenseur_2= torch.rand(1,7)
second_tenseur_2

tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [49]:
produit_2 = tenseur_random_2 @ second_tenseur_2.T
produit_2,produit_2.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [50]:
torch.manual_seed(1234)
tensor_gpu1 = torch.rand(2,3).to(device)
tensor_gpu2 = torch.rand(2,3).to(device)
tensor_gpu1,tensor_gpu2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [51]:
produit_gpu = tensor_gpu1 @ tensor_gpu2.T
produit_gpu

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [52]:
produit_gpu2 = torch.matmul(tensor_gpu1,tensor_gpu2.T)
produit_gpu2

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [53]:
max= torch.max (tensor_gpu1)
min = torch.min(tensor_gpu1)
max,min

(tensor(0.7006, device='cuda:0'), tensor(0.0290, device='cuda:0'))

In [54]:
argmax= torch.argmax (tensor_gpu1)
argmin = torch.argmin(tensor_gpu1)
argmax,argmin

(tensor(5, device='cuda:0'), tensor(0, device='cuda:0'))

In [55]:
torch.manual_seed(7)
tenseur_bizarre = torch.rand(1,1,1,10)
torch.manual_seed(7)
tenseur_bizarre1 = torch.rand(10)
tenseur_bizarre , tenseur_bizarre1

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))

In [58]:
import torch
import torch.nn as nn
import torch.optim as optim

# Définition du modèle
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.linear = nn.Linear(in_features=1, out_features=1)

    def forward(self, x):
        return self.linear(x)

# Création du modèle
model = SimpleModel()

# Définition de l'optimiseur et de la fonction de perte
criterion = nn.MSELoss()  # Mean Squared Error Loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Descente de gradient stochastique

# Données d'entraînement (exemples bidimensionnels avec une seule caractéristique)
inputs = torch.tensor([[1.0], [2.0], [3.0], [4.0]], dtype=torch.float32)
targets = torch.tensor([[2.0], [4.0], [6.0], [8.0]], dtype=torch.float32)

# Boucle d'entraînement
epochs = 2000
for epoch in range(epochs):
    # Étape de propagation avant (feedforward)
    predictions = model(inputs)

    # Calcul de la perte
    loss = criterion(predictions, targets)

    # Réinitialisation des gradients
    optimizer.zero_grad()

    # Étape de rétropropagation (backpropagation)
    loss.backward()

    # Mise à jour des paramètres
    optimizer.step()

    # Affichage de la perte à chaque centième itération
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')

# Évaluation du modèle après l'entraînement
with torch.no_grad():
    test_input = torch.tensor([[5.0]], dtype=torch.float32)
    predicted_output = model(test_input)
    print(f'Prediction for input 5.0: {predicted_output.item():.4f}')

Epoch [100/2000], Loss: 0.0141
Epoch [200/2000], Loss: 0.0077
Epoch [300/2000], Loss: 0.0042
Epoch [400/2000], Loss: 0.0023
Epoch [500/2000], Loss: 0.0013
Epoch [600/2000], Loss: 0.0007
Epoch [700/2000], Loss: 0.0004
Epoch [800/2000], Loss: 0.0002
Epoch [900/2000], Loss: 0.0001
Epoch [1000/2000], Loss: 0.0001
Epoch [1100/2000], Loss: 0.0000
Epoch [1200/2000], Loss: 0.0000
Epoch [1300/2000], Loss: 0.0000
Epoch [1400/2000], Loss: 0.0000
Epoch [1500/2000], Loss: 0.0000
Epoch [1600/2000], Loss: 0.0000
Epoch [1700/2000], Loss: 0.0000
Epoch [1800/2000], Loss: 0.0000
Epoch [1900/2000], Loss: 0.0000
Epoch [2000/2000], Loss: 0.0000
Prediction for input 5.0: 9.9993
